const UNPROCESSABLE = 422;
const CONFLICT = 409;
const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const UNAUTHORIZED = 401;
const SUCCESS = 201;
const OK = 200;

module.exports = {
  UNPROCESSABLE,
  BAD_REQUEST,
  UNAUTHORIZED,
  CONFLICT,
  SUCCESS,
  NOT_FOUND,
  OK,
};
